### ISSUE TITLE
3Bricks.bmp is (slightly) corrupt (?)

### ISSUE THREAD

**Issue by nanodeath** [mxgmn/WaveFunctionCollapse#22]
3Bricks.bmp opens fine in C# (Windows, CLR), opens fine in my editor (Paint.NET), but crashes and burns in Java:
```
Exception in thread "main" java.lang.RuntimeException: Failed while trying to read 3Bricks.bmp!
	at com.technicallyvalid.kollapse.Main.runOverlappingModel(Main.kt:74)
	at com.technicallyvalid.kollapse.Main.main(Main.kt:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IndexOutOfBoundsException: off < 0 || len < 0 || off + len > b.length!
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:346)
	at com.sun.imageio.plugins.bmp.BMPImageReader.read8Bit(BMPImageReader.java:1160)
	at com.sun.imageio.plugins.bmp.BMPImageReader.read(BMPImageReader.java:923)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at com.technicallyvalid.kollapse.Main.runOverlappingModel(Main.kt:72)
	... 6 more
```
Might be a damaged header or something. In any case, it'd be nice if someone could open and re-save 3Bricks.bmp in a trusted editor.

**Comment by mxgmn** [comment]
@nanodeath  Yeah, I noticed that, I'll move everything into png today.

**Comment by mxgmn** [comment]
@nanodeath Is it corrupt now?

**Comment by nanodeath** [comment]
I won't be able to test until tonight (another 9 hours or so).

**Comment by nanodeath** [comment]
I've [switched](https://gitlab.com/nanodeath/kollapse/commit/ab0d0e8a4ce5622f5f1e12d909112bf26095e74e) over to the PNGs and everything's working great. I'm going to resolve the issue.
